coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
    patch:
      default:
        target: 60%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
